config/routes.rb
Rails.application.routes.draw do

  get 'store/index'

  resources :products
  resources :carts, only: [:show, :destroy, :update]
  resources :line_items, only: [:create, :destroy]

  root 'store#index', as: 'store'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  accepts_nested_attributes_for :line_items

  after_save :remove_empty_line_items

  delegate :empty?, to: :line_items

  def remove_empty_line_items
    line_items.where(quantity: 0).delete_all
  end

  def add_product(product)
    current_item = find_line_item_by_product_id(product.id)

    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id, price: product.price, quantity: 1)
    end

    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def remove(item)
    if line_items.include?(item)
      line_items.delete(item)
      return true 
    else 
      errors.add(:base, "Unable to remove #{item.title}")
      return false
    end
  end

  private

  def find_line_item_by_product_id(id)
    unsaved_item = line_items.select { |item| item.product_id == id }.first
    return unsaved_item unless unsaved_item.nil?
    return line_items.find_by(product_id: id)
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart

  validates :quantity, numericality: { greater_than_or_equal_to: 0}

  delegate :title, to: :product

  def total_price
    quantity * product.price
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :title, uniqueness: true, length: { minimum: 10,
    messag: "Yo Fool, you need at least 10 characters for title" }
  validates :description, :title, presence: true
  validates :price, numericality: { greater_than: 0 }

  has_many :line_items

  before_destroy :ensure_referenced_by_any_line_item

  def self.latest
    Product.order(:updated_at).last
  end

  private

  def ensure_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :cart_not_found

  def show
    load_cart
    invalid_cart? ? invalid_cart : render('show')
  end

  def destroy
    load_cart
    if invalid_cart?
      invalid_cart
    else
      destroy_cart
      redirect_to store_url
    end
  end

  def update
    load_cart
    update_line_items
    if @cart.save
      redirect_to cart_path(@cart)
    else
      flash[:notice] = 'Could not update your cart'
      render 'show'
    end
  end

  private

  def update_line_items
    @cart.line_items_attributes = line_items_params
  end

  def cart_not_found
    logger.error "Cart was not found with #{params[:id]}"
    redirect_to(store_url, notice: 'Invalid cart')
  end

  def invalid_cart?
    return true if @cart.id != session[:cart_id]
    return false
  end

  def invalid_cart
    logger.error "Attempt to access someone elses cart #{params[:id]}"
    redirect_to(store_url, notice: 'Invalid cart')
  end

  def load_cart
    @cart = Cart.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cart_params
    params.require(:cart)
  end

  def line_items_params
    data = cart_params.permit(line_items_attributes: [:quantity, :id])
    data[:line_items_attributes]
  end

  def destroy_cart
    @cart.destroy
    session[:cart_id] = nil
  end

end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern

  def current_cart
    @cart ||= Cart.find(session[:cart_id])
  end

  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/concerns/store_counter.rb
module StoreCounter
  extend ActiveSupport::Concern

  def store_counter
    session[:store_counter]
  end

  private

  def reset_store_counter
    session[:store_counter] = 1
  end

  def add_to_store_counter
    session[:store_counter] += 1
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include StoreCounter
  include CurrentCart

  before_action :set_cart, only: [:create, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: Proc.new {
    flash[:error] = "Record not found"
    redirect_to_cart
  }

  def create
    puts params
    build_line_item

    respond_to do |format|
      if save_line_item
        format.html { redirect_to store_path }
        format.js { @current_item = @line_item }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    load_line_item
    delete_line_item 
    redirect_to_cart
  end

  private
  
  def delete_line_item
    unless current_cart.remove(@line_item)
      flash[:errors] = current_cart.errors[:base]
    end
  end

  def build_line_item
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)
  end

  def save_line_item
    if @line_item.save
      reset_store_counter
    end
  end

  def redirect_to_cart
    redirect_to cart_path(current_cart)
  end

  def load_line_item
    @line_item ||= LineItem.find(params[:id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  include StoreCounter
  include CurrentCart

  before_action :set_cart
  
  def index
    if store_counter.nil?
      reset_store_counter
    else
      add_to_store_counter
    end

    @products = Product.order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def to_test_id(val)
    val.downcase.gsub(" ", "-")
  end

  def current_cart
    if (controller.respond_to? :current_cart)
      return controller.current_cart
    end
  end

  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display:none"
    end

    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_item_helper.rb
module LineItemHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart_total.html.erb
<tr class="total_line">
  <td colspan="2">Total</td>
  <td clas="total_cell"><%= number_to_currency(cart.total_price) %></td>
</tr>

app/views/carts/_sidebar_cart.html.erb
<table data-test-id="<%= to_test_id "cart table" %>">
  <%= render partial: "line_items/view_line_item", collection: @cart.line_items, as: :line_item %>
  <%= render partial: "carts/cart_total", locals: {cart: cart} %>
</table>

app/views/carts/show.html.erb
<% if notice %>
  <p id="notice"><%= notice %></p>
<% end %>

<h2>Your Cart</h2>

<% if @cart.empty? %>
  <div>
    Your cart is empty, go add some items.
  </div>
<% end %>

<table>
  <tr>
    <th>Quantity</th>
    <th>Title</th>
  </tr>
  <%= form_for @cart, method: :put do |cart_form| %>
    <%= render partial: "line_items/edit_line_item", collection: @cart.line_items, as: :item, locals: {parent_form: cart_form} %>

    <tr>
      <td colspan="4"><hr /></td>
    </tr>

    <%= render partial: "carts/cart_total", locals: {cart: @cart} %>

    <tr>
      <td><%= cart_form.submit("Update cart") unless @cart.empty? %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Cools Online Store</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
    <!-- <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %> -->
    <%= csrf_meta_tags %>
  </head>
  <body class='<%= controller.controller_name %>'>

    <div id="banner">
      <%= image_tag("logo.png") %>
      <%= @page_title || "Pragmatic Bookshelf" %>
    </div>

    <div id="columns">
        <div id="side">
        <% if current_cart %>
          <%= hidden_div_if current_cart.empty?, id: "cart" do %>
            <%= render partial: "carts/sidebar_cart", locals: { cart: @cart }%>
          <% end %>
h       <% end %>

        <ul>
          <li><a href="<%= store_url %>">Home</a></li>
          <% if current_cart %>
            <li><a href="<%= cart_path(current_cart) %>">Your Cart</li>
          <% end %>
          <li><a href="http://www..../faq">Questions</a></li>
          <li><a href="http://www..../news">News</a></li>
          <li><a href="http://www..../contact">Contact</a></li>
          <li class="date"><%= DateTime.now.to_s %></li>
        </ul>
      </div>

      <div id="main">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/line_items/_edit_line_item.html.erb
<tr>
  <%= parent_form.fields_for "line_items", item do |line_form| %>
    <td><%= line_form.text_field :quantity, 'data-test-id': to_test_id(item.title + '-quantity') %> &times;</td>
    <td><%= line_form.label :line_item, "#{item.title}" %></td>
    <td class="item_price"><%= number_to_currency(item.total_price) %></td>
    <td><%= link_to 'Remove all', item, method: :delete, class: :button %></td>
  <% end %>
</tr>
<br />

app/views/line_items/_view_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item" data-test-id="<%= to_test_id(line_item.product.title) %>" >
<% else %>
  <tr data-test-id="<%= to_test_id(line_item.product.title) %>" >
<% end %>
  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.product.title  %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>
  <td><%= button_to 'Remove', line_item, method: :delete, data: { confirm: "Are you sure?"} %>
</tr>

app/views/line_items/create.js.erb
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000) }
$('#cart').html("<%= escape_javascript render(partial: "carts/sidebar_cart", locals: {cart: @cart}) %>")
$('#current_item').css({'background-color': '#88ff88'}).
    animate({'background-color':'#114411'}, 1000);

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, lines: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <% @products.each do |product| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
      <td>
        <%= image_tag(product.image_url, class: 'list_image') %>
      </td>
      <td class="list_description">
        <dl>
          <dt><%= product.title %></dt>
          <dd><%= truncate(strip_tags(product.description), length: 80) %></dd>
        </dl>
      </td>
      <td class="list_actions">
        <%= link_to 'Show', product %> <br/>
        <%= link_to 'Edit', edit_product_path(product) %> <br/>
        <%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>
<br/>
<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @product.image_url %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/store/index.html.erb
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>

<h1>Your Pragmatic Catalog</h1>
<% if session[:store_count] %>
  <p>Count: <%= pluralize(session[:store_count], 'visit') %></p>
<% end %>
<% cache ['store', Product.latest] do %>
  <% @products.each do |product| %>
    <% cache ['entry', product] do %>
      <div class="entry" data-test-id=<%= to_test_id(product.title) %>>
        <%= link_to line_items_path(product_id: product), method: :post, remote: true do %>
          <%= image_tag(product.image_url) %>
        <% end %>
        <h3><%= product.title %></h3>
        <%= sanitize(product.description) %>
        <div class="price_line">
          <span class="price"><%= number_to_currency product.price %></span>
          <%= button_to 'Add to Cart', line_items_path(product_id: product), remote: true %>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>